[language-server.pyright]
command = "pyright-langserver"
args = [ "--stdio" ]

[[language]]
name = "python"
auto-format = true
formatter = { command = "black", args=["--quiet", "-"] }
language-servers = [ "pyright" ]
